release:
  github:
    owner: chanyipiaomiao
    name: devops-api
  name_template: '{{.Tag}}'
  draft: true
builds:
  - main: main.go
    binary: devops-api
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - 386
  - ldflags: -s -w -X devops-api/common.BuildDate={{.Date}} -X devops-api/common.CommitHash={{.Commit}} -X devops-api/common.AppVersion={{.Version}} -X devops-api/common.GoVersion={{.Env.GO_VERSION}}
  env:
      - CGO_ENABLED=0
archive:
  format: tar.gz
  wrap_in_directory: true
  replacements:
    amd64: 64-bit
    darwin: macos
    linux: linux
  files:
    - LICENSE
    - README.md
    - conf/*.conf
  format_overrides:
    - goos: windows
      format: zip